# Generated by Django 5.1.6 on 2025-02-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0002_service_barberservice'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, help_text="Calculated based on services' estimated time", null=True, verbose_name='End Time')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='barbers.barber', verbose_name='Barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_services', to='barbers.barberservice', verbose_name='Barber Service')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_services', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'unique_together': {('reservation', 'barber_service')},
            },
        ),
    ]
