# Generated by Django 5.1.6 on 2025-02-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barberservice_unique_together_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(help_text='Services included in this reservation', related_name='reservations', to='barbers.service', verbose_name='Services'),
        ),
        migrations.DeleteModel(
            name='ReservationService',
        ),
    ]
