# Generated by Django 5.1.6 on 2025-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_services_delete_reservationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
