# Generated by Django 5.1.6 on 2025-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
