# Generated by Django 5.1.6 on 2025-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('X', 'Cancelled'), ('R', 'Requested'), ('A', 'Accepted'), ('D', 'Declined')], default='R', max_length=1),
        ),
    ]
