# Generated by Django 5.1.6 on 2025-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='Path to profile image file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
