# Generated by Django 5.1.6 on 2025-02-07 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('estimated_time', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='barbers.barber', verbose_name='Barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='barbers.service', verbose_name='Service')),
            ],
            options={
                'unique_together': {('barber', 'service')},
            },
        ),
    ]
