# Generated by Django 5.1.6 on 2025-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barber_profile_picture_barber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Barber profile image', null=True, upload_to='barbers/'),
        ),
    ]
