# Generated by Django 5.1.6 on 2025-02-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_service_barberservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barberservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='barberservice',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='barberservice',
            name='service',
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barbers', to='barbers.service', verbose_name='Services Offered'),
        ),
    ]
