# Generated by Django 5.1.6 on 2025-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('H', 'Hair Services'), ('N', 'Nail Services'), ('G', 'Grooming Services')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
