# Generated by Django 5.1.6 on 2025-02-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
